apiVersion: apps/v1
kind: Deployment
metadata:
  name: birdsquawk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: birdsquawk
  template:
    metadata:
      labels:
        app: birdsquawk
    spec:
      containers:
        - name: birdsquawk
          image: jramadan/birdsquawk:0.0.2

---
apiVersion: v1
kind: Service
metadata:
  name: birdsquawk-clusterip
spec:
  selector:
    app: birdsquawk
  ports:
    - name: birdsquawk
      protocol: TCP
      port: 5000
      targetPort: 5001