apiVersion: v1
kind: Pod
metadata:
  name: birdsquawk
spec:
  containers: 
    - name: birdsquawk
      image: jramadan/birdsquawk:0.0.1

---
apiVersion: v1
kind: Service
metadata:
  name: birdsquawk-clusterip
spec:
  selector:
    app: birdsquawk
  ports:
    - name: birdsquawk
      protocol: TCP
      port: 5000
      targetPort: 5001