apiVersion: apps/v1
kind: Deployment
metadata:
  name: peep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peep
  template:
    metadata:
      labels:
        app: peep
    spec:
      containers:
        - name: peep
          image: jramadan/peep:0.0.1

---
apiVersion: v1
kind: Service
metadata:
  name: peep
spec:
  selector:
    app: peep
  ports:
    - name: peep
      protocol: TCP
      port: 5001
      targetPort: 5001