apiVersion: v1
kind: Pod
metadata:
  name: peep
spec:
  containers: 
    - name: peep
      image: jramadan/peep:0.0.1

---
apiVersion: v1
kind: Service
metadata:
  name: peep-clusterip
spec:
  selector:
    app: peep
  ports:
    - name: peep
      protocol: TCP
      port: 5001
      targetPort: 5001